// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car.id.server.DbConfig;

namespace car.id.server.Migrations
{
    [DbContext(typeof(CarIdDataContext))]
    partial class CarIdDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("car.id.server.Models.CarInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<string>("Brand");

                    b.Property<string>("Capacity");

                    b.Property<string>("Color");

                    b.Property<string>("DReg");

                    b.Property<string>("Dep");

                    b.Property<string>("DepCode");

                    b.Property<string>("Fuel");

                    b.Property<string>("Kind");

                    b.Property<string>("MakeYear");

                    b.Property<string>("ModelName");

                    b.Property<string>("NRegNew");

                    b.Property<string>("OperCode");

                    b.Property<string>("OperName");

                    b.Property<string>("OwnWeight");

                    b.Property<string>("Person");

                    b.Property<string>("Purpose");

                    b.Property<string>("RegAddrKoatuu");

                    b.Property<string>("TotalWeight");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
